### ISSUE TITLE
Hero Carousel- Mobile View issue

### ISSUE THREAD

**Issue by Kummu007** [hlxsites/aldevron#179]
Hi Team, 

Found an issue in mobile view, Please look into the below snap and do the needful.

![image](https://github.com/hlxsites/aldevron/assets/117751754/ec944cdb-c756-4eae-92ef-ee69a9ad3c33)

![image](https://github.com/hlxsites/aldevron/assets/117751754/c9561cfb-fd88-4ee9-8268-7fdecc672a13)

![image](https://github.com/hlxsites/aldevron/assets/117751754/34826a29-5a5c-4fa0-bd38-cabcb8275138)

**Comment by Nasirahamad88** [comment]
If I change the button position then okay?

**Comment by teshukatepalli1** [comment]
Fixed Please validate @Kummu007

**Comment by teshukatepalli1** [comment]
Hi @Kummu007  As per the previous implementation the content is not displaying in correctly. There is an overlap on white background and the content is hiding to the bottom without image. To fix that we have increased the content to 70%. So that to display content we will have more space and visible to the customer. 

<img width="738" alt="Screenshot 2023-12-07 at 12 32 15 PM" src="https://github.com/hlxsites/aldevron/assets/147175528/1eb15fa5-3d7a-4b82-bd86-79d064061f10">

**Comment by Kummu007** [comment]
@teshukatepalli1 Thanks for the update, as per the above thread," to display content we will have more space and be visible to the customer"

So, I'm closing the ticket.

![image](https://github.com/hlxsites/aldevron/assets/117751754/fd39436b-0b01-4f42-aa66-5c446d2a7e1b)
